### ISSUE TITLE
PSweight requires data

### ISSUE THREAD

**Issue by ASallin** [thuizhou/PSweight#1]
Hello,
I was playing around with PSweight, using pre-estimated p.scores and outcome predicted values. However, the function does not allow for data = NULL, yname = NULL and zname = NULL when ps.estimate and out.estimate are given (which does not correspond to the vignette, that states that data is optional).
Thanks

**Comment by thuizhou** [comment]
Hi, the predicted outcome is for weighting augmentation use only. You still need to supply yname, and data for the observed outcome. zname is needed, as the estimated propensity alone can not conduct proper weighting, it needs to be combined with treatment assignment(z).

**Comment by ASallin** [comment]
Thanks for the reply, I realized I was a bit fast in reading the vignette and confused by not seeing an option to enter Y and Z as vectors (rather than as characters referring to their variables in data) and by seeing zname as potentially NULL. Reading now more carefully, it all makes sense. My apologies.
