### ISSUE TITLE
contrasts can be applied only to factors with 2 or more levels

### ISSUE THREAD

**Issue by anischaba** [thuizhou/PSweight#11]
Hello, 

I experience an issue using this package. Indeed when I want to use the SumStat function, I have this error message. I think it is just a problem of coding variables, but I intended various possibilities without finding the solution. The treatment group is GCSF == "2"

str(fasneut$GCSF)
Factor w/ 2 levels "1","2": 2 2 2 2 2 2 2 2 2 2 ...

str(fasneut$sexe)
Factor w/ 2 levels "1","2": 1 2 2 2 1 1 1 2 2 2 ...

str(fasneut$age)
int [1:83] 32 8 41 19 24 10 12 31 32 27 ...

ps.any <- GCSF ~ age + sexe

bal.any <- SumStat(ps.formula = ps.any, data = fasneut, weight = c("IPW", "overlap", "treated"))

**Error in if (xi > xj) 1L else -1L : valeur manquante là où TRUE / FALSE est requis**

I have the same kind of problem when I am searching for ATO. 

ato.any <- PSweight(ps.formula = ps.any, yname = "DC_hospit",data = fasneut, weight = "overlap")
**Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : contrasts can be applied only to factors with 2 or more levels**

thank you for your precious help 

Anis

**Comment by thuizhou** [comment]
Hi, 
Please check out our paper for the correct use of PSweight,
https://arxiv.org/pdf/2010.08893.pdf.

also check out the following example (psdata is included in the package), it can deal with factors.
psdata1<-psdata
psdata1$trt<-factor(psdata1$trt)
psdata1$cov6<-factor(psdata1$cov6)
SumStat(ps.formula = trt~cov5+cov6, data = psdata1, weight = c("IPW", "overlap", "treated"))

another possible issue could be with the data fasneut, as our package don't take tibble, but matrix and data frame only.
