### ISSUE TITLE
Problem with bootstrap when using ps.estimate instead of ps.formula

### ISSUE THREAD

**Issue by rw417** [thuizhou/PSweight#12]
Hi Tianhui,

There seems to be a problem with `bootstrap` when I use `ps.estimate` in stead of `ps.formula` in `PSweight()`.

When I set `bootstrap=FALSE`, `PSweight()` returns the point estimates. However, when I set `bootstrap=TRUE`, I get this error message that suggests that `zname` does not subset data correctly:
``Error in `[.data.frame`(data, , zname) : undefined columns selected``

This only happens when I provide external PS estimates. Everything is fine when I use `ps.formula`.

Would you mind taking a look?

Thanks!

**Comment by rw417** [comment]
By the way, I just found out that even though the function spits out the error message, it seems to still be able to calculate the ATE and the bootstrap standard errors.

**Comment by thuizhou** [comment]
bootstrap can only be used with ps.formula. since your propensity is already estimated and are regarded as fixed values, we don't bootstrap over it.

**Comment by rw417** [comment]
Oh, I had thought the package bootstraps to take samples of the ATE only. Just to make sure I'm understanding correctly, seems like the package bootstraps to take samples of the raw data, and then uses the sampled raw data to calculate PS and ATE?

**Comment by thuizhou** [comment]
that is correct

**Comment by rw417** [comment]
Thanks!
