### ISSUE TITLE
Difference in estimated Weighted Augmented ATT compared to PSW

### ISSUE THREAD

**Issue by GeoBer** [thuizhou/PSweight#13]
I have used PSW to estimate a weighted augmented estimator of ATT treatment effects and I find a difference to the results from PSweight, using the same model in both cases (glm, family="binomial")

**Comment by thuizhou** [comment]
Check out their internal function pst-internal.R, line 524. type='response' is missing in the predict function.

**Comment by GeoBer** [comment]
Dear Tanhui,

Many thanks for your prompt response. Actually line 524 goes to the outcome model in the augmented estimator (which is where the discrepancy was). The mistake is not using type=’response’ AND not using information on the family.

Thank you so much! This was a great catch.

Georgina
