### ISSUE TITLE
Error passing tibbles to SumStat

### ISSUE THREAD

**Issue by ghost** [thuizhou/PSweight#14]
I was getting an error (shown below) in `SumStat`.

I did a bit of debugging and I am pretty sure that it's due to how columns were being indexed; `data[, zname]` behaves differently for base `data.frame`s vs. tibbles (`data[[zname]]` behaves the same for both). If you decide not to change the code, passing a tibble wrapped in `as.data.frame` works fine. I'm seeing this in version 1.1.7 (the latest on CRAN), but I haven't tested the development version here on GitHub.

``` r
library(PSweight)

ps.any <- Dany ~ white + maemp + as.factor(scht) + as.factor(qmab) + as.factor(qmab2) + as.factor(qvab) + as.factor(qvab2) + paed_u + maed_u + agepa + agema + sib_u + paed_u * agepa + maed_u * agema

NCDS_tibble <- dplyr::as_tibble(NCDS)

# This won't work
bal.any <- SumStat(ps.formula = ps.any, data = NCDS_tibble,
                   weight = c("IPW", "overlap", "treated"))
#> Warning in Ops.factor(xi, xj): '>' not meaningful for factors
#> Error in if (xi > xj) 1L else -1L: missing value where TRUE/FALSE needed

# This is okay
bal.any <- SumStat(ps.formula = ps.any, data = as.data.frame(NCDS_tibble),
                   weight = c("IPW", "overlap", "treated"))
```

<sup>Created on 2022-05-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by eamoncaddigan** [comment]
Ah, and I'm using PSweight 1.1.6. I can't upgrade easily right now but if this is fixed in 1.1.7 (already on CRAN) I apologize!

**Comment by thuizhou** [comment]
Please use all PSweight function in data.frame. It is not compatible with tibbles.

**Comment by eamoncaddigan** [comment]
Would you accept a PR that addressed this? I think I could make the fix.
