### ISSUE TITLE
very small weights

### ISSUE THREAD

**Issue by rdefaccio** [thuizhou/PSweight#2]
I was noticing very small IPT and OV weights when using PSWeight. For the OV weights my range was 0.00000521 to 0.000306 and for IPT 0.0001422 to 0.00178. I tried to replicate the IPT weights "by hand" and was getting very different weights, ranging from 1.005 to 11.383. 

For the "by-hand" calculation i used 1/(prop score) for those treated and 1/(1-propscore) for those in the controls.

Is there a subtlety to the IPT calculations that I am missing here?

**Comment by ASallin** [comment]
It seems that PSweight uses the Hajek normalization when computing the weights. Would that explain the difference between your weights and the weights from PSweight?
