### ISSUE TITLE
Really small p-values

### ISSUE THREAD

**Issue by MingzeDong** [thuizhou/PSweight#7]
I am trying to do causal analysis in genomic data. I realized in the default setting of p value computation in PSweight, really small p values (<1e-16) are treated as zeros. Is it possible to give values to these small p values with PSweight for better visualization in volcano plot? Thank you so much!

**Comment by thuizhou** [comment]
yes, if you save the summary of the estimator(summary(PSweight(...))), it is a list. the component called estimates in the list gives the original scale of p-value

**Comment by MingzeDong** [comment]
Thank you for your reply. My problem is, when I use summary()$estimates, the p value would be zero when it is small. I hope to have a way to output smaller p-values, such as $p.value in t-test.

**Comment by MingzeDong** [comment]
I think I see where the problem is. In original code, we have "p.value<-2*(1-pnorm(abs(est.h/se.h)))", and 1-pnorm will be equal to 0 in R when the term is small. Maybe we can convert the 1-pnorm term into pnorm(-) to avoid the issue.
