### ISSUE TITLE
�-� not meaningful for factors and NA error

### ISSUE THREAD

**Issue by cwy20030** [thuizhou/PSweight#8]
Hi,

I noticed that the library cannot handle prespecified factorial variables. I usually pre-specify my variables first prior to any computation. 

Another issue found is that the algorithm seems to have trouble handling NA values in a data.frame.

**Comment by thuizhou** [comment]
it does not handle NA, you need to impute first or remove the missing obs. As for factors, it handles. Check out the case below.

a<-rbinom(n=1000,size=1,prob=0.5)
b<-factor(rep(c('1','2','d','e'),250))
c<-rnorm(1000)
dt<-data.frame(a,b,c)
PSweight(a~b,yname='c',data=dt)

**Comment by cwy20030** [comment]
Hi,

This is what I got from my analysis with a 3-level factor. 

4: In Ops.factor(ytmp, wttmp) : ‘*’ not meaningful for factors
5: In Ops.factor(y, mu[i]) : ‘-’ not meaningful for factors

**Comment by thuizhou** [comment]
Check out this example where the trt and independent variable are both factor with multiple levels, it still works.  

a<-rbinom(n=1000,size=1,prob=0.5)+rbinom(n=1000,size=1,prob=0.5)
a<-as.factor(a)
b<-factor(rep(c('1','2','d','e'),250))
c<-rnorm(1000)
dt<-data.frame(a,b,c)
PSweight(a~b,yname='c',data=dt)
